"""Apply lightweight auto-fixes generated by policy findings."""
from __future__ import annotations

import subprocess
from pathlib import Path

from rich.console import Console

from giton import interactive, policies

console = Console()


def apply_fix(
    finding: policies.Finding,
    cwd: Path,
    *,
    yes: bool = False,
) -> bool:
    """Run the fix command for a single finding.

    Returns True if the command succeeded (returncode 0).
    """
    if not finding.fix:
        return False

    prompt = (
        f"Apply fix for [bold]{finding.policy}[/bold]?\n"
        f"  [dim]{finding.fix}[/dim]"
    )
    if not yes and not interactive.confirm(prompt):
        return False

    result = subprocess.run(
        finding.fix,
        shell=True,
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        if result.stderr:
            console.print(f"[red]fix failed:[/red] {result.stderr.strip()}")
        return False
    console.print(f"[green]✓ fixed[/green] {finding.policy}")
    return True


def apply_all(
    findings: list[policies.Finding],
    cwd: Path,
    *,
    yes: bool = False,
) -> tuple[int, int]:
    """Apply every available fix in *findings*.

    Returns (applied_count, available_count).
    """
    available = [f for f in findings if f.fix]
    if not available:
        console.print("[dim]no auto-fixes available[/dim]")
        return 0, 0

    applied = 0
    for f in available:
        if apply_fix(f, cwd, yes=yes):
            applied += 1
    return applied, len(available)
