flowchart TD
%% generated in 0.00s
    examples__advanced["examples.advanced<br/>5 funcs"]
    examples__basic["examples.basic<br/>2 funcs"]
    src__giton["src.giton<br/>82 funcs"]
    examples__advanced ==>|6| src__giton
    examples__basic -->|2| src__giton
